- hosts: localhost
  tasks:
#    - add_host:
#        name: test-host
#        group: test-group
#        ansible_user: test-user

    - add_host:
        name: item.hostname #test-host
        group: item.group #test-group-dom
        ansible_user: item.ansible_user #test-user-dom
        on_dom: item.on_dom
      with_items: "{{ host_to_use }}" 

    - debug:
        var: item.hostname
      with_items: "{{ host_to_use }}"

- hosts: test-servers
  gather_facts: no
  tasks:
    - debug:
        var: item
      with_items:
        - '{{ ansible_user }}'
        - '{{ inventory_hostname }}'
        - '{{ var_set }}'
        - '{{ ansible_password }}'

- hosts: test-host
  gather_facts: no
  tasks:
    - debug:
        var: item
      with_items:
        - '{{ ansible_user }}'
        - '{{ inventory_hostname }}'
        - '{{ var_set }}'
        - '{{ ansible_password }}'
