- hosts: localhost
  tasks:
#    - add_host:
#        name: test-host
#        group: test-group
#        ansible_user: test-user

    - debug:
        var: item.host.hostname  #item.hostname #figure our way to correctly refer to dictionary value
      with_items: "{{ host_to_use }}"

    - add_host: 
        name: "{{ item.host.hostname }}"
        group: "{{ item.host.group }}"
        ansible_user: "{{ item.host.ansible_user }}"
        on_dom: "{{ item.host.on_dom }}"
      with_items: "{{ host_to_use }} "

#    - debug:
#        var: item.hostname
#      with_items: "{{ host_to_use }}"

- hosts: test-servers
  gather_facts: no
  tasks:
    - debug:
        var: item
      with_items:
        - '{{ ansible_user }}'
        - '{{ inventory_hostname }}'
        - '{{ var_set }}'
        - '{{ ansible_password }}'
      when: on_dom
#- hosts: test-host
#  gather_facts: no
#  tasks:
#    - debug:
#        var: item
#      with_items:
#        - '{{ ansible_user }}'
#        - '{{ inventory_hostname }}'
#        - '{{ var_set }}'
#        - '{{ ansible_password }}'
